name: Release
run-name: Create release by ${{ github.actor }}
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Building image..."
      - run: sudo ${{ github.workspace }}/make.sh 64
      - run: sudo ${{ github.workspace }}/make.sh 128
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.gz"
