name: Test
run-name: Test by ${{ github.actor }}
on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Building image..."
      - run: sudo ${{ github.workspace }}/make.sh
